geojson= {
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "properties":{
            "Luas":5000,
            "Harga":300000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               101.45132308825778,
               0.6859889286088628
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":600,
            "Harga":1550000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.435",
               "0.5124"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1600,
            "Harga":1360000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1820,
            "Harga":1547000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":284,
            "Harga":850000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1272,
            "Harga":750000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":415,
            "Harga":650000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":400,
            "Harga":880000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":210,
            "Harga":650000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":5690,
            "Harga":6828000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":523,
            "Harga":230000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":460,
            "Harga":115000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.47516",
               "0.46717"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":18527,
            "Harga":2779050000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.39768",
               "0.65189"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":600,
            "Harga":400000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.39888",
               "0.48788"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":453,
            "Harga":165000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":465,
            "Harga":9000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4425227",
               "0.5284009"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":6000,
            "Harga":42000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":336,
            "Harga":152000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.3969767136",
               "0.44868780071632"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":450,
            "Harga":45000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":153,
            "Harga":99450000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.45935273819",
               "0.57658944328415"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":600,
            "Harga":225000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":400,
            "Harga":400000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":40000,
            "Harga":14000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.3958665",
               "0.5404513"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1015,
            "Harga":1000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":200,
            "Harga":170000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4185",
               "0.47965"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":450,
            "Harga":150000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.45296216691",
               "0.56732043433918"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":5100,
            "Harga":12750000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.420961",
               "0.498374"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":2516,
            "Harga":2800000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":540,
            "Harga":300000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.3996",
               "0.57504"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":8000,
            "Harga":6000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.44558",
               "0.47972"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":895,
            "Harga":230000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.47655",
               "0.57596"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":56000,
            "Harga":42000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.45561273876",
               "0.45910758268192"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":11415,
            "Harga":17122500000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":389,
            "Harga":291000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.439593",
               "0.47367"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1800,
            "Harga":1350000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":46533,
            "Harga":13959900000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.45853",
               "0.49507"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1000000,
            "Harga":59000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.40534",
               "0.52805"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":500000,
            "Harga":32500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4468",
               "0.571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1417,
            "Harga":425250000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.40054941601",
               "0.45490979570895"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":5000,
            "Harga":300000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.396",
               "0.62063"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":290,
            "Harga":65000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4023469",
               "0.5788967"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":225,
            "Harga":110000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1656,
            "Harga":2160000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4501772",
               "0.4726793"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":800000,
            "Harga":5500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.39697",
               "0.51723"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":403,
            "Harga":180000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":2500,
            "Harga":9000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4452",
               "0.50034"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":200,
            "Harga":45000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1000,
            "Harga":490000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4477793",
               "0.5070677"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":658,
            "Harga":150000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":300,
            "Harga":200000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.5082711457",
               "0.48813434125571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":522,
            "Harga":500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4717922",
               "0.4802062"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":20000,
            "Harga":350000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":3625,
            "Harga":3625000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":579,
            "Harga":2000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.48717",
               "0.49944"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":542,
            "Harga":450000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":500,
            "Harga":525000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.47165",
               "0.50355"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":900,
            "Harga":400000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4468",
               "0.571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":200,
            "Harga":55000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.53448",
               "0.50823"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":10575,
            "Harga":27000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.40702",
               "0.46401"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":493,
            "Harga":147900000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.452298",
               "0.573597"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":420,
            "Harga":525000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":299,
            "Harga":200000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.446418",
               "0.464743"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":150,
            "Harga":27500000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.39534622192",
               "0.51737797891918"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":216,
            "Harga":245000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":522,
            "Harga":500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4079779",
               "0.5230021"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":7400,
            "Harga":17020000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4231606",
               "0.4381302"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1000000,
            "Harga":50000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4477793",
               "0.5070677"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":42000,
            "Harga":2940000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.457",
               "0.5402"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1400000,
            "Harga":850000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4894946",
               "0.4859958"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":6700,
            "Harga":2010000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":595,
            "Harga":1900000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":12101,
            "Harga":6353025000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4468",
               "0.571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":715,
            "Harga":1787500000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.42717595015",
               "0.52080693480613"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":10000,
            "Harga":3500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":520,
            "Harga":260000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":10460,
            "Harga":2000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":3000,
            "Harga":24000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4320842",
               "0.5035385"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":70000,
            "Harga":38500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.53831242003",
               "0.50422758789918"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":27000,
            "Harga":27000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.45338650528",
               "0.459383841336"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":200,
            "Harga":45000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":509,
            "Harga":559900000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.415917",
               "0.631778"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":659,
            "Harga":724900000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "33",
               "20"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":119,
            "Harga":125000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.37032993017",
               "0.44601289267929"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":882,
            "Harga":1300000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":8400,
            "Harga":33600000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":223,
            "Harga":45000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":8915,
            "Harga":49032500000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":3440,
            "Harga":1634000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":542,
            "Harga":406500000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.41043",
               "0.5184"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":856,
            "Harga":500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.38209",
               "0.4323"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":517,
            "Harga":336050000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "24",
               "25"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":450,
            "Harga":190000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":3264,
            "Harga":2121600000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.47192",
               "0.57416"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":272,
            "Harga":350000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.43688868359",
               "0.54440995993917"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1278,
            "Harga":1917000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4628176",
               "0.4837453"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1764,
            "Harga":1500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":300,
            "Harga":160000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.45",
               "0.533333"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":4000,
            "Harga":48000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1308,
            "Harga":1438800000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":506,
            "Harga":303600000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.43568",
               "0.51362"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":225,
            "Harga":400000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":749,
            "Harga":516810000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":548,
            "Harga":900000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4452",
               "0.51416"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":14514,
            "Harga":3047940000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.475084",
               "0.497561"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":121200,
            "Harga":54540000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":200,
            "Harga":170000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.43414",
               "0.4255"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":480,
            "Harga":350000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1000,
            "Harga":800000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":200,
            "Harga":55000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":12000,
            "Harga":17500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":9300,
            "Harga":57500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.44210990471",
               "0.50802404269767"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":777,
            "Harga":330000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4468",
               "0.571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":20000,
            "Harga":1500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":9550,
            "Harga":1910000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":630,
            "Harga":400000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.47060163408",
               "0.47912504326252"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":546,
            "Harga":819000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1700,
            "Harga":10000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":540,
            "Harga":1300000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":716,
            "Harga":1500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4468",
               "0.571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":3450,
            "Harga":4485000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.40696",
               "0.49331"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":600,
            "Harga":350009099
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4468",
               "0.571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":7200,
            "Harga":7000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1050,
            "Harga":3000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":15000,
            "Harga":9150000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4291",
               "0.4646"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":240000,
            "Harga":3500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.43718",
               "0.52115"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":2600,
            "Harga":7200000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":10000,
            "Harga":2250000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.41660544894",
               "0.602756540139"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1113,
            "Harga":2200000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":987,
            "Harga":1300000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4070716",
               "0.5366874"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1240,
            "Harga":3000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.36475",
               "0.48108"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":9086,
            "Harga":5000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.45",
               "0.533333"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1700,
            "Harga":20400000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":2500,
            "Harga":8500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":100000,
            "Harga":60000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4306",
               "0.5254"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":600,
            "Harga":250000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4468",
               "0.571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":800,
            "Harga":1300000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.43391036114",
               "0.53731140214421"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":38000,
            "Harga":2700000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.39566",
               "0.62136"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":450,
            "Harga":160000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4468",
               "0.571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":650,
            "Harga":465000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4468",
               "0.571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":14000,
            "Harga":7770000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.40683",
               "0.57787"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":180,
            "Harga":63000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":486,
            "Harga":1225000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":959,
            "Harga":750000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":9550,
            "Harga":1719000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.40057",
               "0.52155"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1274,
            "Harga":916006000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.36488",
               "0.47761"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":40000,
            "Harga":4500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.31466",
               "0.43868"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":6700,
            "Harga":1200000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4667",
               "0.50552"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":4122,
            "Harga":2800000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.36934",
               "0.44987"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1,
            "Harga":100000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.36475",
               "0.48108"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1500,
            "Harga":4500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.44684",
               "0.57074"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":10000,
            "Harga":55000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":19950,
            "Harga":2493750000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":9555,
            "Harga":5255250000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4468",
               "0.571"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":700,
            "Harga":1400000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1274,
            "Harga":891800000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":939,
            "Harga":1300000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.46356124878",
               "0.5041517622763"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":19110,
            "Harga":955500000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.45983",
               "0.42717"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":2400,
            "Harga":8400000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.418848",
               "0.445528"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1192,
            "Harga":17000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1010,
            "Harga":353500000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":940,
            "Harga":1000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":10460,
            "Harga":26150000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.567149",
               "0.509615"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":40000,
            "Harga":4000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":994,
            "Harga":1491000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.3735646",
               "0.4759122"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1300,
            "Harga":800000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.45",
               "0.533333"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":6598,
            "Harga":23093000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1100,
            "Harga":9700000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.45063",
               "0.50998"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":11900,
            "Harga":4250000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":3800,
            "Harga":21000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.50452",
               "0.49699"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":80000,
            "Harga":4000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1765,
            "Harga":1412000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":561,
            "Harga":1800000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":9000,
            "Harga":5900000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1000,
            "Harga":1200000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1220,
            "Harga":1342000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":625,
            "Harga":2500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4634685",
               "0.5139355"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":3397,
            "Harga":4585950000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1896,
            "Harga":14220000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":2911,
            "Harga":2008590000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":4500,
            "Harga":20
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.41780162964",
               "0.46969023802568"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":9200,
            "Harga":6900000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":13,
            "Harga":7896600000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1300,
            "Harga":6500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":7400,
            "Harga":8700000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.39129",
               "0.46814"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":12000,
            "Harga":20400000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.39661",
               "0.47171"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":7000,
            "Harga":19000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":5000,
            "Harga":47500000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":6000,
            "Harga":3000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.40817",
               "0.46399"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":3450,
            "Harga":4485000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.40696",
               "0.49331"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":243,
            "Harga":1944000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":900,
            "Harga":1300000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.437284",
               "0.4959195"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":987,
            "Harga":1300000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4070716",
               "0.5366874"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1184,
            "Harga":1539200000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.44887",
               "0.44722"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":460,
            "Harga":115000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.47516",
               "0.46717"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":42000,
            "Harga":2940000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.457",
               "0.5402"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":272,
            "Harga":350000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.43688868359",
               "0.54440995993917"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":2600,
            "Harga":7200000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1220,
            "Harga":1342000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":8400,
            "Harga":33600000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":3397,
            "Harga":4585950000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1896,
            "Harga":14220000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":8915,
            "Harga":49032500000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":7200,
            "Harga":7000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":542,
            "Harga":450000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1800,
            "Harga":1350000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1274,
            "Harga":891800000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":546,
            "Harga":819000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":11900,
            "Harga":4250000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":4000,
            "Harga":48000000000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Luas":1308,
            "Harga":1438800000
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               "101.4166",
               "0.54"
            ]
         }
      }
   ]
}
geojsonFix={
   "type":"FeatureCollection",
   "features":[]
}

for x in geojson['features']:
    luas=x['properties']['Luas']
    harga=x['properties']['Harga']
    lat=x['geometry']['coordinates'][0]
    lon=x['geometry']['coordinates'][1]
    newContent={
         "type":"Feature",
         "properties":{
            "Luas":luas,
            "Harga":harga
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               float(lat),
               float(lon)
            ]
         }
      }
    geojsonFix['features'].append(newContent)
print(geojsonFix)

